version: '3'
services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    image: "cypress/included:4.1.0"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "cypress/included:4.1.0"
    command: "--browser chrome"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json

  # this container will run Cypress test using Firefox browser
  e2e-firefox:
    image: "cypress/included:4.1.0"
    command: "--browser firefox --config video=false"
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json